List<String> restaurants = [
  "McDonald's",
  "Burger King",
  "Wendy's",
  "Taco Bell",
  "KFC",
  "Subway",
  "Domino's Pizza",
  "Pizza Hut",
  "Dunkin' Donuts",
  "Starbucks",
  "Chipotle Mexican Grill",
  "Sonic Drive-In",
  "Arby's",
  "Panda Express",
  "In-N-Out Burger",
  "Chick-fil-A",
  "Jimmy John's",
  "Dairy Queen",
  "Five Guys",
  "Little Caesars",
];
